login just before pulling

diff --git a/.github/workflows/docker_deploy.yml b/.github/workflows/docker_deploy.yml
--- a/.github/workflows/docker_deploy.yml
+++ b/.github/workflows/docker_deploy.yml
@@ -84,25 +84,20 @@ jobs:
       image_digest: ${{ steps.image_data.outputs.image_digest }}
       image_timestamp: ${{ steps.image_data.outputs.image_timestamp }}
     steps:
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v4
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-
-      - name: Check if image blsq/${{ needs.config.outputs.repo }}:${{ inputs.image_tag }} exists on Docker Hub
-        run: |
-          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
-            "https://hub.docker.com/v2/repositories/blsq/${{ needs.config.outputs.repo }}/tags/${{ inputs.image_tag }}")
-          if [ "$STATUS" != "200" ]; then
-            echo "::error::Image blsq/${{ needs.config.outputs.repo }}:${{ inputs.image_tag }} not found on Docker Hub"
-            exit 1
-          fi
-          echo "Image blsq/${{ needs.config.outputs.repo }}:${{ inputs.image_tag }} found"
+#      - name: Check if image blsq/${{ needs.config.outputs.repo }}:${{ inputs.image_tag }} exists on Docker Hub
+#        run: |
+#          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
+#            "https://hub.docker.com/v2/repositories/blsq/${{ needs.config.outputs.repo }}/tags/${{ inputs.image_tag }}")
+#          if [ "$STATUS" != "200" ]; then
+#            echo "::error::Image blsq/${{ needs.config.outputs.repo }}:${{ inputs.image_tag }} not found on Docker Hub"
+#            exit 1
+#          fi
+#          echo "Image blsq/${{ needs.config.outputs.repo }}:${{ inputs.image_tag }} found"
 
       - name: Pull the image and inspect it to get the digest and timestamp
         id: image_data
         run: |
+          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
           docker pull blsq/${{ needs.config.outputs.repo }}:${{ inputs.image_tag }}
           echo "image_digest=$(docker image inspect blsq/${{ needs.config.outputs.repo }}:${{ inputs.image_tag }} --format='{{index .RepoDigests 0}}' | cut -d ':' -f2)" >> $GITHUB_OUTPUT
           echo "image_timestamp=$(docker image inspect blsq/${{ needs.config.outputs.repo }}:${{ inputs.image_tag }} --format='{{ index .Created }}')" >> $GITHUB_OUTPUT
